server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/railway_ticket_reservation
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
